# config file for vehicle geometry

# Note: also see vehicle_footprint.yaml

# car wheelbase (distance between front and rear wheels)
wheelbase: .196

# car track (distance between left and right wheels)
track: 0.135

# car dimensions (note redundant data in vehicle_footprint.yaml)
length: 0.378
width: 0.192
height: 0.185
