# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from deep_learning/Burak.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Burak(genpy.Message):
  _md5sum = "30cabddebe002ba107d2c72ae8a924cb"
  _type = "deep_learning/Burak"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 type
float32 steering
bool hasObstacle
"""
  __slots__ = ['type','steering','hasObstacle']
  _slot_types = ['int32','float32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       type,steering,hasObstacle

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Burak, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.type is None:
        self.type = 0
      if self.steering is None:
        self.steering = 0.
      if self.hasObstacle is None:
        self.hasObstacle = False
    else:
      self.type = 0
      self.steering = 0.
      self.hasObstacle = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_ifB().pack(_x.type, _x.steering, _x.hasObstacle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.type, _x.steering, _x.hasObstacle,) = _get_struct_ifB().unpack(str[start:end])
      self.hasObstacle = bool(self.hasObstacle)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_ifB().pack(_x.type, _x.steering, _x.hasObstacle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.type, _x.steering, _x.hasObstacle,) = _get_struct_ifB().unpack(str[start:end])
      self.hasObstacle = bool(self.hasObstacle)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_ifB = None
def _get_struct_ifB():
    global _struct_ifB
    if _struct_ifB is None:
        _struct_ifB = struct.Struct("<ifB")
    return _struct_ifB
